electron/docs-parser

src/__tests__/__snapshots__/markdown-helpers.spec.ts.snap, src/__tests__/markdown-helpers.spec.ts, src/markdown-helpers.ts
This PR adds support for really complex inner types.  We currently support simple things like `Promise<T>` or `Function<A, B>` but if you gave it something fun like
```
Function<P1<InnerP1, AnotherInnerP1[]>, P2<(InnerP2 | AnotherInnerP2<SuperDeepP2, EvenDeeperP2>)[]>, R<Foo>>
```
It would just give up and cry in a corner.  This was because we were using things like `.split(',')` and regexps to get the inner type.  Unfortunately regexps have no concept of depth (you can't write a parser with regexps).  So now we go token by token and understand depth to correctly handle these complicated structures.
This PR comes with a bunch of tests which validate that this logic works as expected 👍
=> fix: support complex and nested inner types

src/DocsParser.ts
Some documents need to be included in the repo but not yet ready to be published, this PR provides a way to ignore those documents when parsing.
This is needed by https://github.com/electron/electron/pull/18952.
=> feat: ignore modules with "(Draft)" in title

src/__tests__/markdown-helpers.spec.ts, src/markdown-helpers.ts
This PR allows for string literals to use both backticks and normal quotes, as well as for users to optionally use oxford commas in specifying the last string literal.
Before, only the following worked:
```
Can be `record-until-full`, `record-continuously`, `record-as-much-as-possible` or `trace-to-console`.
```
With this change, all of the following now work:
```
Can be `record-until-full`, `record-continuously`, `record-as-much-as-possible` or `trace-to-console`.
```
```
Can be 'record-until-full', 'record-continuously', 'record-as-much-as-possible' or 'trace-to-console'.
```
```
Can be 'record-until-full', 'record-continuously', 'record-as-much-as-possible', or 'trace-to-console'.
```
To produce:
```
recording_mode?: ('record-until-full' | 'record-continuously' | …
```
=> fix: allow normal quotes as well as oxford commas

src/DocsParser.ts, src/ParsedDocumentation.ts, src/__tests__/markdown-helpers.spec.ts, src/block-parsers.ts, src/markdown-helpers.ts
This exposes a new key `additionalTags` on every API structure (properties, events, methods, structure keys, etc.) for the tags we put on the API in `electron/electron.
These tags look like
```md
```
The resultant JSON looks like this
The intention is to put this information in `@` annotations in the ts-defs
=> feat: expose OS/stability tags in the API structure

src/DocsParser.ts, src/block-parsers.ts, src/markdown-helpers.ts
This ensures that types like Object | String don't both try to enumerate the sub keys.  Previously this resulted in a correctly typed object and a `String` with "possibleValues" equal to the keys of the object (which is straight up wrong).
At a high level now instead of passing around the raw TypedKey array we pass around a TypedKeyList struct which has a `consumed` property.  Calling `consumeTypedKeyList` on that struct will mark `consumed` as `true` and ensure no other call can consume that list.
=> fix: ensure that sub keys can only be consumed by a single type (the first one)

README.md
Adds a URL to an empty markdown link.
=> docs: Add missing Markdown link to README.md

src/bin.ts
Removes an unnecessary check to ensure the `name` property in the `package.json` file of a directory `docs-parser` is being run against is exactly equal to `electron`.
This change lowers the barrier for other projects to adopt docs-parser.
=> fix: Remove unnecessary package.json `name` valid

src/DocsParser.ts, src/ParsedDocumentation.ts, src/__tests__/markdown-helpers.spec.ts, src/markdown-helpers.ts
read process fields correctly.
=> feat: read process fields (#14)

src/DocsParser.ts, src/ParsedDocumentation.ts, src/bin.ts, src/index.ts
This is mostly for projects like `node` that export multiple packages from their API instead of multiple modules from a single package.
=> feat: add a multi-package mode so that classes are exported under a module instead of at the top level of the API

src/markdown-helpers.ts
Improves the context provided when hitting the error that can be found [here](https://github.com/electron/docs-parser/blob/master/src/markdown-helpers.ts#L672).
Here's an example of the output before this PR:
```
✖ Generating API in directory: "/Users/cyren/GitHub/node-docs-parser"
An error occurred while processing: "/Users/cyren/GitHub/node-docs-parser/docs/api/v8.md"
AssertionError: Expected key token to be an inline code block: expected 'text' to equal 'code_inline'
```
And here's an example after:
```
$ electron-docs-parser --dir ./
✖ Generating API in directory: "/Users/cyren/GitHub/node-docs-parser"
An error occurred while processing: "/Users/cyren/GitHub/node-docs-parser/docs/api/v8.md"
AssertionError: Expected key token to be an inline code block at "Returns: {string} The …
```
=> fix: improve provided context in key token error

src/__tests__/markdown-helpers.spec.ts, src/markdown-helpers.ts
Prompted by https://github.com/electron/electron/issues/21231.
The old Regex:
Matches:
but doesn't match:
owing to a typo where it expected space after the `.` in order to match:
This fixes that by changing the regex to remove the extra space requirement after the period.
cc @MarshallOfSound
=> fix: return type incorrectly checking periods

README.md, src/bin.ts, src/index.ts
Allow parsing for smaller modules like https://github.com/codebytere/node-mac-userdefaults, whose docs are all located in the main README file.
Example usage: 
```sh
electron-docs-parser --dir=./ --useReadme
```
cc @MarshallOfSound
=> feat: allow useReadme flag for parsing only the README

src/DocsParser.ts
The generated output on Windows had invalid URLs since it had Windows paths in it. PR simply ensures the paths are always POSIX-style.
=> fix: generate correct URLs on Windows

src/__tests__/markdown-helpers.spec.ts
Looks like an `it.only` snuck into a commit and was causing most of the tests to be skipped.
=> chore: re-enable accidentally disabled tests

src/constants.ts
Current version is generating incorrect URLs by duplicating `docs/api/`.
=> fix: correct GitHub repo base URL

src/ParsedDocumentation.ts, src/__tests__/markdown-helpers.spec.ts, src/block-parsers.ts, src/markdown-helpers.ts
This is intended as a solution to the issue mentioned described in electron/algolia-indices#227. The code in that repo can't accurately create URLs from `electron-api.json` because some of the necessary information isn't included. By adding a new field that loop can be closed, and the search indexes should be robust against changes in docs conventions. I decided on `urlFragment` rather than setting the full `websiteUrl` to avoid duplication, and because the URL fragment should be applicable to both the `websiteUrl` and `repoUrl`.
=> feat: urlFragment for methods/properties/events

src/__tests__/__snapshots__/markdown-helpers.spec.ts.snap, src/__tests__/markdown-helpers.spec.ts, src/markdown-helpers.ts
This allows constructions such as:
```md
* `bar` Function<{type: 'a'} | { type: 'b', extraThing? 'c' }>
```
=> fix: respect {} in safe typestring splitting

package.json, src/markdown-helpers.ts, yarn.lock
The version of `@types/markdown-it` wasn't consistent with `markdown-it`, which didn't seem correct. This rectifies that. Require a slight code change when the correct types were used.
=> chore: use matching version of @types/markdown-it

src/constants.ts
Tags on the `electron/electron` repository begin with 'v'.
=> fix: include 'v' prefix on version in GitHub URL

.circleci/config.yml, package.json, src/__tests__/__snapshots__/markdown-helpers.spec.ts.snap, src/__tests__/markdown-helpers.spec.ts, yarn.lock
=> fix: update dependencies to clean up yarn audit

src/ParsedDocumentation.ts, src/block-parsers.ts, src/markdown-helpers.ts
This adds support for these two new forms of syntax for declaring event objects:
```markdown
Returns:
* `event` Event<>
* `url` string - The URL the frame is navigating to.
* `isSameDocument` boolean - Whether the navigation happened without changing
document. Examples of same document navigations are reference fragment
navigations, pushState/replaceState, and same page history navigation.
* `isMainFrame` boolean - True if the navigation is taking place in a main frame.
* `frame` WebFrameMain - The frame to be navigated.
* `initiator` WebFrameMain (optional) - The frame which initiated the
navigation, which can be a parent frame (e.g. via `window.open` with a
frame's name), or null if the navigation was not initiated by a frame. This
can also be null if the initiating frame was deleted …
```
=> feat: add new Event support for extensible params

src/ParsedDocumentation.ts, src/__tests__/markdown-helpers.spec.ts, src/markdown-helpers.ts
This adds support for reading the utility process from `Process:` blocks.
This is needed to add new API to the utility process. Currently, the only API in the utility process is not exported, [doc](https://github.com/electron/electron/blob/713d8c4167a07971775db847adca880f49e8d381/docs/api/parent-port.md?plain=1#L5).
See https://github.com/electron/electron/pull/40017 for an example of adding new API to the utility process that will need this change.
=> feat: add utility process

src/__tests__/block-parsers.spec.ts
This was apparently lying around on my machine, whoops
=> test: add block-parsers test

package.json
This is based on Jest since we need tests to pass:
https://github.com/jestjs/jest/blob/05deb8393c4ad71e19be2567b704dfd3a2ab5fc9/package.json#L171-L173
=> chore: add `engines.node` to package.json

src/__tests__/markdown-helpers.spec.ts, src/markdown-helpers.ts
Fixes #93
It's non trivial to support this syntax so let's spit out a helpful error message instead.
=> fix: better handling of union return types

src/__tests__/markdown-helpers.spec.ts, src/markdown-helpers.ts
Fixes #97
Fixes #98
The comment in #98 was correct, the regex method here isn't great and is one of the few regex smells we have left in this module. This rewrites our string enum extractor as a token-parser state-machine thing. Hope the comments I left are helpful, I'll note that this method _already_ had really solid tests that helped me catch edge cases and this PR adds even more.
=> fix: support double quote string enum

.circleci/config.yml, .gitattributes, .husky/pre-commit, jest.config.js, package.json, src/DocsParser.ts, src/ParsedDocumentation.ts, src/__tests__/markdown-helpers.spec.ts, src/bin.ts, src/block-parsers.ts, src/index.ts, src/markdown-helpers.ts, tsconfig.json, yarn.lock
BREAKING CHANGE: We now require node 20 or higher
This is an internal only package so a good candidate for early updates to be ESM compatible, makes it easier to update packages and maintain moving forward. Has no impact on consumption of this module as we exclusively use it via the CLI in the electron repo.
=> refactor: convert to ESM + update all dependencies
